### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by jeyeroddz** [tdtgit/sitemap-warmer#54]
**Describe the bug**
Hey @tdtgit, thanks for the tool, I hope that I'll go through all the obstacles but now I have the following: 
I've installed everything following your instruction on Debian 9
When I tried to launch the warming process I received:

root@domainname:~# warmup https://domainname.com -a                                                                                                              
/usr/bin/env: node: No such file or directory

BTW. How can I add different sitemaps? I have sitemap_en.xml, sitemap_de.xml and sitemap_fr.xml and they are located in different folders

**Comment by tdtgit** [comment]
Hi,

Thanks for your report. I'm not sure how you install the NodeJS (before install my warmer app), can you try:
1. Reinstall NodeJS 12 or higher as guided [here](https://computingforgeeks.com/install-node-js-on-debian-linux-system/) 
OR
1. Run command `ln -s /usr/bin/nodejs /usr/bin/node` as described [here](https://stackoverflow.com/questions/26320901/cannot-install-nodejs-usr-bin-env-node-no-such-file-or-directory)

I tried create a new fresh Debian 9 instance, install NodeJS 12 and everything is still working fine. 
```
root@vultr:~# npm i datuan-sitemap-warmer -g
/usr/bin/warmup -> /usr/lib/node_modules/datuan-sitemap-warmer/index.js
+ datuan-sitemap-warmer@1.3.0
added 39 packages from 70 contributors in 7.048s
root@vultr:~# warmup https://datuan.dev -a
12/7/2021, 3:40:13 PM [INFO]  main: 📬 Getting sitemap from https://datuan.dev/sitemap.xml
```
In some cases, for Debian instance, you may need to install git cli before install my warmer app:
```
apt install git
```

-------------------------------
At the moment, you can use direct link to your sitemap like below example:
```
warmup https://domainname.com/sitemap_en.xml -a
warmup https://domainname.com/yourfolder/sitemap_de.xml -a
```
But I will design a way to load multiple sitemap URLs in next releases soon.

**Comment by jeyeroddz** [comment]
thanks for your help, I succeed in that but now I'm playing around with options and I have message "killed" after 15 min. There are only 1500 urls in the 1st sitemap, should I tune some timeout?

2021-12-07T19:53:03.053Z [DEBUG] warmer:   ⚡️ Warming https://domainname.com/page  deflate
Killed                                                                                                                                                                                                                                                                                                                                                 
root@domain:~# warmup https://domainname.com/1_ru_0_sitemap.xml --all --no-css --no-js --no-brotli -q                                                                                                                                                                                                                                                 
12/7/2021, 10:02:17 PM [INFO]  main: � Getting sitemap from https://domainname.com/1_ru_0_sitemap.xml
2021-12-07T20:02:18.529Z [INFO]  warmer: ✅  Done. Prepare warming all URLs
Killed                                                                                                                                                                                                                                                                                                                                                 
root@domain:~#

**Comment by tdtgit** [comment]
Interesting. Never play with that huge amount of URLs. Let me check.

**Comment by jeyeroddz** [comment]
@tdtgit hey! Have you tried to warm up more than 2000 URLs?

**Comment by tdtgit** [comment]
I found some Russian website's sitemaps that have about 1500+ URLs and 1.5MB in size. Run pretty slow (because of my internet connection to Russian server) but still run fine. If you don't mind, please send your real sitemap URL to my email hi@duonganhtuan.com for my further checks.

**Comment by jeyeroddz** [comment]
I sent you the email

**Comment by jeyeroddz** [comment]
@tdtgit hey! Any news? Have you checked warming with my sitemap?

**Comment by tdtgit** [comment]
Checked your sitemap and all run fine, take times but it can finish without any issue. You may want to check your server specs (the server run warmup job and your internet connection)
```
2021-12-14T16:17:19.883Z [INFO]  warmer: 📫 Done! Warm up total 3472 URLs (included 1672 images) and 42 assets. Have fun!
```

**Comment by tdtgit** [comment]
Any updates for your case? I will close this issue and you can re-open at any time.

**Comment by jeyeroddz** [comment]
The issue was in lack of memory. Thanks
